### ISSUE TITLE
routes var in generate section will auto generate sitemap content

### ISSUE THREAD

**Issue by sandalwoodsh** [nuxt-community/sitemap-module#102]
If routes are not defined here:
sitemap: {
    path: "/sitemap.xml",
    hostname: "https://example.com"
  }

AND a variable "routes" is found in the generate section, then the routes will be added automatically to the sitemap file. 

generate: {
    routes: function() {
      return axios
        .get(“blahblahblah”)
        .then(res => {
          const routes = [];
          […]

          return routes;
        });
    }
  }

**Comment by NicoPennec** [comment]
yes, it's a feature as explain in the [doc](https://github.com/nuxt-community/sitemap-module#routes-optional---array--function)
> **routes (optional) - array | function**
>
> Default: `[]` or `generate.routes` value from your nuxt.config.js

**Comment by sandalwoodsh** [comment]
Thanks, Nicolas. It's great that it does that. I guess my question was how
can I add other parameters to each route so that it saves out to the file
as well. I can't save anything else other than the route.
