### ISSUE TITLE
Allow init routes manually in nuxtServerInit?

### ISSUE THREAD

**Issue by everyx** [nuxt-community/sitemap-module#104]
Thus, when in SSR mode, we can get robots.txt data from api and  dynamically  generate robots.txt.

like [nuxt-community/gtm-module](https://github.com/nuxt-community/gtm-module)

> ## GTM Initialisation
> If you want to block Google Tag Manager before user directly allows (GDPR realisation or other), you can set autoInit option to false and then manually enable using $gtm.init().
>
> Note: All events will be still buffered in data layer but won't send until init() method getting called.

**Comment by NicoPennec** [comment]
@everyx  I not sur to understand. What do you mean by "Allow init routes"?

**Comment by NicoPennec** [comment]
duplicate https://github.com/nuxt-community/sitemap-module/issues/105
