### ISSUE TITLE
Get routes config in routes function

### ISSUE THREAD

**Issue by padinko** [nuxt-community/sitemap-module#107]
### What problem does this feature solve?

We are using named dynamic routes (path can change, but name doesn't, so all occurences of path in app are changed automaticly). Now we use api to generate dynamic routes, but can't access actual router config, so we can only staticly add this routes.. but when path changed, we need to change sitemap `routes` too. It will be great if we can use named routes and change only path and sitemap will still work without change

### What does the proposed changes look like?

there will be router config in `router` parameter (probably second, so callback is still usable)

-or-

there will be some `this` in router function where we can access router config

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c83">#c83</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Hi @padinko 

I'm not sure to understand your request, but have you take a look to the [**filter**  feature](https://github.com/nuxt-community/sitemap-module#filter-optional---function)?

It's a function that allow to filter or update the routes just before sitemap generation. On the `routes` parameter, you can find the name or path of each route, and thus update them dynamically.

Let me know if enough for your need.

eg. config.nuxt.js
```js
  sitemap: [
    {
      filter ({ routes }) {
        console.log(routes)
        return routes
      }
    }
  ]
````

console output
```js
  {
    name: 'index',
    path: '/',
    component: '/Users/user/project/pages/index.vue',
    chunkName: 'pages/index',
    url: '/'
  },
 ...
```
