### ISSUE TITLE
Does not see child page when generating the sitemap

### ISSUE THREAD

**Issue by Julien76** [nuxt-community/sitemap-module#11]
Hi,

Thanks for this module.
I have an issue and do not know if it's a bug or not.

I have some children pages which are not dynamic:

Here is the list of url:
 
    /
    /singlePageA   
    /singlePageB
    /parentA/
    /parentA/childA
    /parentA/childB

Here is the folder set-up in the directory `pages`

    index.vue
    singlePageA.vue   
    singlePageB.vue
    parentA.vue
    parentA/
      index.vue    
      childA.vue
      childB.vue
   
Now if I run @nuxtjs/sitemap with the default value and just set `generate: true`, then only the following route are considered in the sitemap.xml:
    
    /
    /singlePageA   
    /singlePageB
    /parentA
    
Missing routes are:

    /parentA/    <--- Note the trailing forward slash
    /parentA/childA
    /parentA/childB

My understanding is that as those routes are "static" children routes, they should be considered by the `@nuxtjs/sitemap module`. Am I wrong?
Do I have to define them manually?
If so, do you a know an easy way to generate a route list (json file) and inject it in the `@nuxtjs/sitemap options`

Thanks.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/sitemap-module/issues/c12">#c12</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Fixed in release [v0.2.1](https://github.com/nuxt-community/sitemap-module/blob/dev/CHANGELOG.md#021-2019-03-12)
