### ISSUE TITLE
Support server request context

### ISSUE THREAD

**Issue by Mosharush** [nuxt-community/sitemap-module#111]
### What problem does this feature solve?

Hi,
I am using the module to create a dynamic sitemap on a large project.
So, the routes requested from the backend by `routes` option as a function using Axios to get routes.

Because it is a large project, the backend works around 1 minute to fetch & generate all routes.
I check on google's advice to return status 503 with `Retry-After` header to tell bots to return later when the data ready.

Now my issue is I got the error by Axios, but I can't handle it to the user because I no have access to Node Request Context.

I will glad full if you can expose the context to the routes function handler.

Thank you in advance.

### What does the proposed changes look like?

Add the request context to routes function handler call.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c86">#c86</a>)</em></sub></div>

**Comment by assaffa** [comment]
+1

**Comment by MatiKonenYad2** [comment]
+1

**Comment by NicoPennec** [comment]
Hi @Mosharush 

By design, the routes function cannot access to the request context, because the function is executed (or not) by the cache mechanism.

But, since [Nuxt v2.13.0](https://fr.nuxtjs.org/guide/release-notes/#v2.13.0) you can throw an error with custom headers (eg. "Retry-after").  
See more in these [issue](https://github.com/nuxt/nuxt.js/issues/7213) and [PR](https://github.com/nuxt/nuxt.js/pull/7214) about that feature.

Example for your initial request:

```js
sitemap: {
  routes: async () => {
    try {
      const { data } = await axios.get('https://example.com/')
      return data
    } catch (error) {
      // add custom headers
      error.headers = { 'Retry-After': 120 }
      throw error
    }
  }
}
```

**Comment by workingxx92** [comment]
@NicoPennec 
How to get req.headers.host before call api

**Comment by NicoPennec** [comment]
@workingxx92  as explain previously you cannot : "By design, the routes function cannot access to the request context, because the function is executed (or not) by the cache mechanism". Sorry.

**Comment by rylax** [comment]
> @workingxx92 as explain previously you cannot : "By design, the routes function cannot access to the request context, because the function is executed (or not) by the cache mechanism". Sorry.

Ist here any known workaround to getting the host before the routes call?
