### ISSUE TITLE
Cant create different lastmod values for different sitemaps

### ISSUE THREAD

**Issue by icodefuture** [nuxt-community/sitemap-module#112]
I want to add different lastmod values to individual sitemaps.

```
sitemap: {
		path: '/sitemap_index.xml',
    	        xslUrl: '/sitemap.xsl',
		sitemaps: 
		[
			{
				path: '/article-sitemap.xml',
				lastmod: '2020-04-20',
                         }
                ]
}
```
However the generated sitemap is just having loc field only at this URL - sitemap_index.xml

**Comment by NicoPennec** [comment]
@icodefuture Thank you for the bug report.

It should be fixed on the next release.
