### ISSUE TITLE
allow `sitemap` to be a function

### ISSUE THREAD

**Issue by tmorehouse** [nuxt-community/sitemap-module#115]
### What problem does this feature solve?

Similar to `@nuxtjs/robots` module, it would be nice if the sitemaps nuxt.config.js entry would allow for a function rather than just an object.

### What does the proposed changes look like?

No changes to existing process, except to allow `sitemaps` property to be a function

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c92">#c92</a>)</em></sub></div>

**Comment by tmorehouse** [comment]
Also, it would be nice to be able to set `sitemap` property to `false` to disable generation of a sitemap for a particular build, rather then generating an empty sitemap file.

**Comment by NicoPennec** [comment]
This feature is available since the release [2.3.0](https://github.com/nuxt-community/sitemap-module/blob/dev/CHANGELOG.md#230-2020-05-11)

Thank @tmorehouse for your proposal 🙏

**Comment by tmorehouse** [comment]
Thanks!
