### ISSUE TITLE
Generate sitemap when API data changes?

### ISSUE THREAD

**Issue by hackuun** [nuxt-community/sitemap-module#12]
Is it possible to regenerate sitemap if I change my API data without rerunning `npm run build`?

I mean, Nuxt by itself doesn't need to rebuild everytime I add/change article. It just fetch new data.
Can this be done with this sitemap module?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/sitemap-module/issues/c9">#c9</a>)</em></sub></div>

**Comment by TomFrajer** [comment]
Check readme and look for: Function which returns a Promise

Is it what you are looking for?

**Comment by iamdubx** [comment]
@TomFrajer axios is already returns a promise. I am not sure I am following what do you mean.

**Comment by NicoPennec** [comment]
The `sitemap-module` have a cache of 15 minutes (by default) : https://github.com/nuxt-community/sitemap-module#cachetime

Then the `sitemap.xml` will be rebuild on next call.
