### ISSUE TITLE
can't use as a devDependency

### ISSUE THREAD

**Issue by xerosanyam** [nuxt-community/sitemap-module#120]
it should be mentioned somewhere that it should not be a dev dependency! :)
thanks for the amazing work.

**Comment by NicoPennec** [comment]
First, thank you for your support 🙏 

The [installation](https://github.com/nuxt-community/sitemap-module#installation) section in the README seems clear about it, no? The flag "--save-dev" is not used.

**Comment by xerosanyam** [comment]
many packages say install as prod dependency when they can be used as dev dependency. Also, the dependency itself **feels** as if it should be used on the dev side, hence the confusion.
Just a suggestion, feel free to skip. thanks! :)
