### ISSUE TITLE
CacheTime with nuxt generate

### ISSUE THREAD

**Issue by mornir** [nuxt-community/sitemap-module#126]
So if I understand the docs correctly, the cacheTime property doesn't do anything when using `nuxt generate`?
Does the cache get automatically invalidated when the website is regenerated?

**Comment by NicoPennec** [comment]
Yes, it is correct. On `nuxt generate` the cache will be have no effect.

The cache system is only used by a server middleware at the second call in SSR mode. But on generate mode, the sitemap xml generator will call it only one time.

**Comment by mornir** [comment]
Thanks for the quick answer and for this great module! 😃
