### ISSUE TITLE
allow option to disable usage of publicPath

### ISSUE THREAD

**Issue by lautr** [nuxt-community/sitemap-module#129]
### What problem does this feature solve?

The usage of `base.publicPath` to use as the host for the sitemap does not make sense when it's also used to set up the CDN for Nuxt Assets, which is its recommended usage.

Therefore it would make sense to disable this feature to allow nuxt/sitemap to regularly decide it's host, or provide a way to access the request to set host manually.

Right now the host name needs to be hard coded which makes it's usage hard for multi domain deployments and tests in feature environments.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c98">#c98</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Hi @lautr 

I understand your request, but I'm not sure to understand the use case.
Can you give more details to reprice and try to solve it?

Your are on ssr, spa or generate mode?
Your assets are deployed on a single URL (ex. http://cdn.example.com) and your web app on multiple hostname (ex. http://www.example.com, http://www.example.org, ...), correct ?

If you can share your `nuxt.config.js` it will be perfect for helping me ;)

**Comment by NicoPennec** [comment]
@lautr as a workaround, you can set the hostname to a [_falsy_](https://developer.mozilla.org/en-US/docs/Glossary/falsy) value in your `nuxt.config.js` file:

```js
  sitemap: {
    hostname: false
  },
```

**Comment by lautr** [comment]
@NicoPennec 

Ah, perfect that did the trick!
Would make sense to add that to the documentation imho, and yes, my scenario was as you described.

**Comment by NicoPennec** [comment]
@lautr Yes, you're right!

It was a mistake to apply this default value on hostname. It will be removed on the release 3.x of the sitemap module. I just updated the README to mark it as deprecated on 2.x.

Thanks for your report
