### ISSUE TITLE
Generate a meta link (<link rel="sitemap")

### ISSUE THREAD

**Issue by qathom** [nuxt-community/sitemap-module#13]
Hello,

First of all, thank you for making this module!
I was wondering why there isn't an option to generate a meta link automatically? Is it appropriate to pass through the module for this functionality?

For example:
```html
<link rel="sitemap" href="/sitemap.xml" />
```

**Comment by NicoPennec** [comment]
no, because it's useless, the root `/sitemap.xml` is a conventional path for web crawlers

but you can add the meta link in your `nuxt.config.js`
```js
  head: {
    link: [
      { rel: 'sitemap', href: '/sitemap.xml' }
```
