### ISSUE TITLE
Support routes from "generate.routes" output

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/sitemap-module#133]
### What problem does this feature solve?

Ease-of-use. Would be cool if it generated sitemap on deploy from output already fetched here in my nuxt.config.js generate.routes property, with exception of the "payload" data, so I don't have to repeat my code, and take extra unnessecary resources on the deploy server.

### What does the proposed changes look like?

Somehow fetch the `generate.routes` output and remove payload property and generate sitemap based on this.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c100">#c100</a>)</em></sub></div>

**Comment by elemikelo** [comment]
I have the same problem, I have to cache the mapped routes and then add them to the module.
The proposal is good.
I think in the hook to map the routes getted in the generate routes and inject them into the sitemap module. 

**humble example** 😛
```
this.nuxt.hooks('generate:done', (generator, errors) => {
     // Assuming routes = [ {route: '...', payload: {} ]
     const routes = await cache.get('routes')

    // maybe this map within the cache method
    const mappedRoutes = routes.map(routes, el => el === 'object' ? (el.route ? { url: 
     el.route } : route) : { url: el }) // maybe this map within the cache method
     
   const sitemap = await createSitemap(options, mappedRoutes)
    ...
})
```

Cheers, Ele

**Comment by simplenotezy** [comment]
Great. Will test it

**Comment by simplenotezy** [comment]
@elemikelo Could you show me where you add this code? I'd like to test it out ;)

**Comment by simplenotezy** [comment]
Looking at https://github.com/nuxt-community/sitemap-module#routes-optional---array--function it seems as though this might already be supported, but it is unclear to me.

> Default: [] or generate.routes value from your nuxt.config.js

Does this mean, if I leave routes empty, it will use the ones from `generate.routes`? Because I have already defined this. Perhaps @NicoPennec or @pi0 would know this

**Comment by NicoPennec** [comment]
Yes, by default the sitemap module will take the `generate.routes` values for the `sitemap.routes`

see default option: https://github.com/nuxt-community/sitemap-module/blob/dev/lib/options.js#L23

**Comment by simplenotezy** [comment]
Ah that's great news. I think the documentation is a little misleading though.
> All static routes (eg. /pages/about.vue) are automatically add to the sitemap, but you can exclude each of them with the exclude property.
For dynamic routes (eg. /pages/_id.vue), you have to declare them with the routes property. This option can be an array or a function.

Perhaps it should be noted like: "routes defined in generate.routes will be automatically used for the sitemap"
