### ISSUE TITLE
i18n rel-alternate-hreflang missing for generated routes

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/sitemap-module#137]
### Version

[2.3.1](https://github.com/sitemap-module/releases/tag/2.3.1)

### Reproduction link

[https://thejewelleryroom.com/sitemap.xml](https://thejewelleryroom.com/sitemap.xml)

### Steps to reproduce

1) Set sitemap configuration like so:
```
	sitemap: {
		hostname: process.env.BASE_URL,
		gzip: true,
		i18n: {
			defaultLocale: 'en',
			locales: ['en', 'da'],
			routesNameSeparator: '___'
		},
```

2) Generate the sitemap

3) Inspect the sitemap.xml

### What is expected ?

><url><loc>https://thejewelleryroom.com/product/product-name</loc><lastmod>2020-06-14T20:01:44.123Z</lastmod><changefreq>daily</changefreq><priority>1.0</priority>
<xhtml:link rel="alternate" hreflang="da" href="https://thejewelleryroom.com/da/produkt/product-name"/> foreach of the different routes</url>

### What is actually happening?

<url><loc>https://thejewelleryroom.com/da/produkt/product-name</loc><lastmod>2020-06-14T20:01:44.123Z</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url>

### Additional comments?

I'm not sure what I am missing or doing wrong; I believe I've done everything according to the documentation. Sitemap may be viewed here: https://thejewelleryroom.com/sitemap.xml

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c104">#c104</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Duplicate https://github.com/nuxt-community/sitemap-module/issues/122

The sitemap module can handle only static routes from nuxt and nuxt-i18n.
You have to create your own i18n dynamic routes for now ([see example](https://github.com/nuxt-community/sitemap-module/issues/122#issuecomment-633424117)).
