### ISSUE TITLE
i18n option only generates <url> for default language

### ISSUE THREAD

**Issue by ems1985** [nuxt-community/sitemap-module#140]
### Version

[2.3.2](https://github.com/sitemap-module/releases/tag/2.3.2)

### Reproduction link

[https://github.com/nuxt-community/sitemap-module/blob/dev/README.md](https://github.com/nuxt-community/sitemap-module/blob/dev/README.md)

### Steps to reproduce

(Please note that the reproduction link, is just as a link to the docs, because the problem is already shown in the i18n docs example.)

When using the i18n option to generate a sitemap, only one `<url>` is generated for all language versions. But, according to a Google post (https://support.google.com/webmasters/answer/189077) there should be a `<url>` created for every page. I know it seems redundant, but I guess thats how it should be.

### What is expected ?

```
 <url>
    <loc>https://example.com/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="https://example.com/"/>
    <xhtml:link rel="alternate" hreflang="es" href="https://example.com/es/"/>
  </url>
 <url>
    <loc>https://example.com/es/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="https://example.com/"/>
    <xhtml:link rel="alternate" hreflang="es" href="https://example.com/es/"/>
  </url>
```

### What is actually happening?

```
 <url>
    <loc>https://example.com/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="https://example.com/"/>
    <xhtml:link rel="alternate" hreflang="es" href="https://example.com/es/"/>
  </url>
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c105">#c105</a>)</em></sub></div>

**Comment by ems1985** [comment]
This is the problem shown in the Google Search Console. I actually have 42 pages, but because of the way the sitemap is generated it only shows 21:

<img width="946" alt="Screenshot 2020-06-19 at 12 42 46" src="https://user-images.githubusercontent.com/34405275/85124730-abdd5080-b22a-11ea-8d50-3f27a580ebbd.png">

**Comment by ems1985** [comment]
This is the problem shown in the Google Search Console. I actually have 42 URLs, but because of the way the sitemap is generated it only shows 21:

![Screenshot 2020-06-19 at 12.42.46.png](https://cmty.s3.eu-west-1.amazonaws.com/101696111/2df3fd00-b21a-11ea-962b-c59b584d72e0.png)

**Comment by ems1985** [comment]
For anyone interested, as a work around you can manually define the routes/URLs for the sitemap as shown here: https://github.com/nuxt-community/sitemap-module/issues/122#issuecomment-633424117

```
// nuxt.config.js

  i18n: {
    locales: ['en', 'de', 'fr'],
    defaultLocale: 'en',
  },
  sitemap: [
    {
      i18n: 'en',
      routes: [
        {
          url: 'test',
          links: ['en', 'fr', 'de'].map((lang) => ({ lang, url: `${lang}/test` })),
        },
        {
          url: 'fr/test',
          links: ['en', 'fr', 'de'].map((lang) => ({ lang, url: `${lang}/test` })),
        },
        {
          url: 'de/test',
          links: ['en', 'fr', 'de'].map((lang) => ({ lang, url: `${lang}/test` })),
        },
      ],
    },
```

**Comment by NicoPennec** [comment]
@ems1985 thanks for your report.

Are you referring to the following sentence?

> Therefore if you have 3 versions of a page, your sitemap will have 3 entries, each with 3 identical child entries

It seems so overkill 😞 , but you right

**Comment by NicoPennec** [comment]
@ems1985 I just published the release [2.4.0](https://github.com/nuxt-community/sitemap-module/blob/dev/CHANGELOG.md#240-2020-06-25) that resolves your issue.   
Let me know if it's good for you now 😉

**Comment by ems1985** [comment]
Just tested it and works like a charm. Thank you so much for your work.

**Comment by miteyema** [comment]
Good work, thanks for this updated version.

I think this will complicate @NicoPennec solution in https://github.com/nuxt-community/sitemap-module/issues/122 when handling dynamic routes...
