### ISSUE TITLE
Disable i18n

### ISSUE THREAD

**Issue by altynbek07** [nuxt-community/sitemap-module#147]
### Version

[v2.4.0 ](https://github.com/sitemap-module/releases/tag/v2.4.0 )

### Reproduction link

[https://github.com/nuxt-community/sitemap-module](https://github.com/nuxt-community/sitemap-module)

### Steps to reproduce

Add i18n
Add sitemap
Configure both according to doc

### What is expected ?

I want to disable autogenerated i18n routes in sitemap. In my `nuxt.config.js` I setted `i18n: false` option in `sitemap ` section:
```js
// nuxt.config.js

{
  modules: [
    ['nuxt-i18n', {
      locales: [
          { code: 'ru', name: "Русский", file: 'ru.js', iso: 'ru-RU' },
          { code: 'kk', name: "Қазақша", file: 'kk.js', iso: 'kk-KZ' },
          { code: 'en', name: "English", file: 'en.js', iso: 'en-US' }
      ],
      defaultLocale: 'ru',
      // and some other i18n options
    }],
    ['@nuxtjs/sitemap', {
      // some other  sitemap options
      i18n: false
    }]
  ]
}
```

### What is actually happening?

Sitemap still generated with i18n routes

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c108">#c108</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Hi @altynbek07,

If you set the `sitemap.i18n` option at `false`, it's only to **not group** i18n routes according this spec: https://support.google.com/webmasters/answer/189077#sitemap. I have tried and with the `false` value it works fine.
Try to set at `true` to understand the difference.

If you only want to hide some routes linked to a language defined from nuxt-i18n, you have to use the "[exclude](https://github.com/nuxt-community/sitemap-module#exclude-optional---string-array)" option or the "[filter](https://github.com/nuxt-community/sitemap-module#filter-optional---function)" option of the sitemap module.

**Comment by altynbek07** [comment]
@NicoPennec Yes, I meant regular i18n routes (attached a screenshot). As a temporary solution, I added this array to the `exclude` option and everything works as I need. But I think this is not the right way:
```javascript
[
  '/kk',
  '/kk/**',

  '/en',
  '/en/**'
]
```

![image](https://user-images.githubusercontent.com/20629188/87184872-3719a580-c302-11ea-8a4a-232243237163.png)

**Comment by NicoPennec** [comment]
@altynbek07 I understand more. If you don't want the routes injected by the i18n module, you just have to declare the sitemap module before it as below:

```js
{
  modules: [
    ['@nuxtjs/sitemap', {
      // some other  sitemap options
      // i18n: false
    }],
    ['nuxt-i18n', {
      locales: [
          { code: 'ru', name: "Русский", file: 'ru.js', iso: 'ru-RU' },
          { code: 'kk', name: "Қазақша", file: 'kk.js', iso: 'kk-KZ' },
          { code: 'en', name: "English", file: 'en.js', iso: 'en-US' }
      ],
      defaultLocale: 'ru',
      // and some other i18n options
    }]
  ]
}
```

**Comment by altynbek07** [comment]
@NicoPennec Yes, It works. Thank you. I'm closing this issue.
