### ISSUE TITLE
Use ENV variables with Nuxt 2.13.x (nuxt static export)

### ISSUE THREAD

**Issue by simondoescode** [nuxt-community/sitemap-module#149]
### What problem does this feature solve?

I am using Nuxt 2.13.3 to develop in universal mode and export it as a static site. 

I am using dotenv to get some enviroment variables and it would be great to use it in conjunction with the `sitemap` module.

Currently I receive the following error:  
```
[sitemap-module] The `hostname` option is mandatory in your config on `spa` or `generate` build mode
```

### What does the proposed changes look like?

```
require('dotenv').config()

export default {
  mode: 'universal',
  target: 'static',

  generate: {
    fallback: true
  },

  env: {
    baseUrl: process.env.BASE_URL || 'http://localhost:3000'
  },

  sitemap() {
    return {
      hostname: process.env.baseUrl,
    }
  },
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c109">#c109</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Hi @SimonFricker 

I don't understand your feature request. Currently you can use dotenv + sitemap module. It works fine with each mode (universal, static, ...)

In addition for your example, you can access to the `env` option by this way:

```js
sitemap() {
    return {
      hostname: this.options.env.baseUrl,
    }
  },
```

**Comment by SimonFricker** [comment]
@NicoPennec Thanks for getting back to me. `baseUrl` is a mask of either `process.env.BASE_URL` (if set) or `http://localhost:3000`

**Comment by simondoescode** [comment]
Ah ok. with `this.options.env.baseUrl,` it worked.
