### ISSUE TITLE
/sitemap.xml returning 404 on production

### ISSUE THREAD

**Issue by TooColline** [nuxt-community/sitemap-module#156]
The sitemap.xml is not being generated on production.

When I go to my site e.g. https://mysite.com/sitemap.xml I get a 404 yet on my dev environment I can see it's generated well. Is there something I am missing?

**Steps I used:**
```
modules: ['@nuxtjs/sitemap'],
sitemap: {
    hostname: process.env.BASE_URL || 'http://localhost:3000',
    defaults: {
      lastmod: new Date(),
      changefreq: 'weekly',
      priority: 1
    }
  }
```
I'm on GCP

**Result:**
When I navigate to localhost:3000/sitemap.xml I can see the sitemap
On production when I navigate to e.g. https://mysite.com/sitemap.xml I get a 404 page not found error

**Comment by TooColline** [comment]
> The sitemap.xml is not being generated on production.
> 
> When I go to my site e.g. https://mysite.com/sitemap.xml I get a 404 yet on my dev environment I can see it's generated well. Is there something I am missing?
> 
> **Steps I used:**
> 
> ```
> modules: ['@nuxtjs/sitemap'],
> sitemap: {
>     hostname: process.env.BASE_URL || 'http://localhost:3000',
>     defaults: {
>       lastmod: new Date(),
>       changefreq: 'weekly',
>       priority: 1
>     }
>   }
> ```
> 
> I'm on GCP
> 
> **Result:**
> When I navigate to localhost:3000/sitemap.xml I can see the sitemap
> On production when I navigate to e.g. https://mysite.com/sitemap.xml I get a 404 page not found error

This was a deployment issue

**Comment by Thyoity** [comment]
I have the same problem, can you describe how did you fixed this issue?

**Comment by TooColline** [comment]
@Thyoity mine was just a deployment issue. The module works just as fine.

After installation all i needed was(for my scenario):
`
sitemap: {
    hostname: '',
    defaults: {
      lastmod: new Date(),
      changefreq: 'weekly',
      priority: 1
    }
  },
`

**Comment by Thyoity** [comment]
I see @TooColline , thanks for your time!
