### ISSUE TITLE
How to create .xml.gz sitemap index ?

### ISSUE THREAD

**Issue by rizkiheryandi** [nuxt-community/sitemap-module#16]
I have web app with lots of URL of single product (let's say it's a e-commerce website).

Let's say i have 60.000 url to save in my sitemap, and i separate that with 2 sitemap.

And each sitemap i wanna compress it with .xml.gz format, to reduce its size.

I can easily do that with PHP (i used laravel), but how to do that with NuxtJs ? (even a pure javascript besides the NuxtJs)

Can someone help me ?

Thank you :)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/sitemap-module/issues/c14">#c14</a>)</em></sub></div>

**Comment by delucis** [comment]
I don’t think this is currently possible with `sitemap-module` alone. It calls [the `.toXml()` method from `sitemap.js`](https://github.com/ekalinin/sitemap.js/blob/72cfbe2c598bac2cd141b61fde09fe2bc946ac12/lib/sitemap.js#L390-L406), which it is built on top of.

`sitemap.js` does implement a [`.toGzip()` method](https://github.com/ekalinin/sitemap.js/blob/72cfbe2c598bac2cd141b61fde09fe2bc946ac12/lib/sitemap.js#L485-L493) although it seems to only use it for sitemap indexes not single sitemap files.

Your best options might be either be to fork `sitemap-module` replacing `.toXml()` calls with `.toGzip()`, or to write a separate Nuxt module, which processes `sitemap-module`’s output using [Node’s built in Gzip tools](https://nodejs.org/api/zlib.html#zlib_zlib). Haven’t tried either, so don’t know how well either of those would work.
