### ISSUE TITLE
router.forEach is not a function

### ISSUE THREAD

**Issue by bootsmann95** [nuxt-community/sitemap-module#161]
I get this error when using npm run generate:

![image](https://user-images.githubusercontent.com/53180316/93777648-577caf00-fc25-11ea-9fe3-9064b38eecff.png)

i guuesh it is beacuse I use the extendRoutes as async call. Have you fixed this?

**Comment by rchl** [comment]
This is fixed in Nuxt 2.14.4 or thereabouts, I believe.

**Comment by bootsmann95** [comment]
Thank you @rchl  worked updating nuxt
