### ISSUE TITLE
sitemap caching?

### ISSUE THREAD

**Issue by airBogdan** [nuxt-community/sitemap-module#164]
I havent posted an issue before and I dont know if this one here is duplicate, but I posted an issue here
https://cmty.app/nuxt/sitemap-module/issues/c118
I read the info and said that I should post issues through the link above.
Do i have to repost it here or posting it on the cmty.app website is enough?

**Comment by NicoPennec** [comment]
answer on https://cmty.app/nuxt/sitemap-module/issues/c118
