### ISSUE TITLE
Sitemap configuration with process.env undefined

### ISSUE THREAD

**Issue by TonyDeplanque** [nuxt-community/sitemap-module#165]
Hello ,

i build my project with NUXT_ENV_x environments variables , but this variables are undefined only in sitemap configuration :/
Nuxt document for environments variables injection : https://fr.nuxtjs.org/docs/2.x/configuration-glossary/configuration-env/#automatic-injection-of-environment-variables

Do you have a solution to use your sitemap configuration with environments variables injection ?

Here my sitemap configuration:

```

 sitemap: {
    defaults: {
      changefreq: 'daily',
      priority: 1,
      lastmod: new Date()
    },
    generate: false,
    hostname: process.env.NUXT_ENV_baseUrl,
    path: '/sitemap.xml',
    cacheTime: 1000 * 60 * 15,
    async routes () {
      let response
      try {
        response = await axios.get(process.env.NUXT_ENV_apiUrl + '/blogs')
      } catch (e) {
        console.log(e)
        return []
      }
      return response.data.map(blog => `/blogs/${blog.slug}`)
    }
  }
```

Nuxt version : 2.14.6
Sitemap module version : 2.4.0

Thank you,

**Comment by NicoPennec** [comment]
Hi @TonyDeplanque 
I haven't reproduced your issue...

I just tried on my end with this short example and it works fine, and with these two ways to defined the var envs:
```js
  sitemap: {
    hostname: process.env.NUXT_ENV_baseUrl,
    routes () {
      return [process.env.NUXT_ENV_apiUrl + '/blogs']
    }
  },
```
```sh
$ export NUXT_ENV_baseUrl=https://example.com
$ NUXT_ENV_apiUrl=api yarn dev
````

How did you initialized with your var envs on your build step?

---

In addition, no longer use the "generate: true/false" option, it's deprecated since the v2.x

**Comment by TonyDeplanque** [comment]
Hi @NicoPennec 

I build my nuxt like that :

`NUXT_ENV_baseUrl=http://localhost:3001 NUXT_ENV_apiUrl=http://localhost:1338 nuxt build`

after i do 

`nuxt start`

This commands are launch with npm.

i put console.log in my routes function. I observe the good variables content during build but not in start command.

i haven't got the probleme when i add my variables in start command like that : 

``NUXT_ENV_baseUrl=http://localhost:3001 NUXT_ENV_apiUrl=http://localhost:1338 nuxt start``

Do we agree that not normal ?

**Comment by NicoPennec** [comment]
@TonyDeplanque 
The `routes` function will be evaluate on module startup, so you have to set the var env on this step as well.

When you declare the var env before the command (eg. `VAR_ENV=xxx <cmd>`), it will be available only in the context of that current command.

So you have to set you var env before each command, or use another way to set it:
- A shell command `export VAR_ENV=xxx`
- The [`env`](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-env/) option on nuxt.config.js (see 
 example here: https://github.com/nuxt-community/sitemap-module/issues/149)
