### ISSUE TITLE
/sitemap 404

### ISSUE THREAD

**Issue by luokunman** [nuxt-community/sitemap-module#166]
I tried various ways to introduce `@nuxtjs/sitemap`, all long `run dev` is ok. `run build` and `run start` is 404

![image](https://user-images.githubusercontent.com/41885648/99767419-f9454d00-2b3d-11eb-811b-2c1fe774dc9c.png)
![image](https://user-images.githubusercontent.com/41885648/99767540-2560ce00-2b3e-11eb-80e9-bc1573dde25f.png)

Online access[https://www.jiangyuanwang.com/sitemap.xml](https://www.jiangyuanwang.com/sitemap.xml) is fail.
I guess `run build` did not produce sitemap.xml

Please help me look at the problem
The problem has been puzzling for a long time
thanks!!!
@NicoPennec

**Comment by NicoPennec** [comment]
duplicate with https://github.com/nuxt-community/sitemap-module/issues/163

I will try to keep grouped the same questions about 404 error ;-)
