### ISSUE TITLE
Add description for each doc page

### ISSUE THREAD

**Issue by atinux** [nuxt-community/sitemap-module#174]
The markdown files are missing the description in metadata, making it pretty bad for SEO:
![Screenshot 2020-12-16 at 15.15.44.png](https://maintainers.s3.fr-par.scw.cloud/Screenshot_2020_12_16_at_15_15_44_203d499f21.png)

cc @geminii

**Comment by Geminii** [comment]
Indeed, i will add it to improve SEO performance 😍
