### ISSUE TITLE
Support Promise for sitemaps option

### ISSUE THREAD

**Issue by hareku** [nuxt-community/sitemap-module#176]
### What problem does this feature solve?

I'm generating the sitemap like the below code.

```ts
export default {
  sitemaps: [
    // ...other routes

    {
      path: '/sitemap-users.xml',
      exclude: ['/**'],
      routes() {
        return axios.get('/api/sitemap-users').then(({ data }) => {
          return data.map(user => `/${user.display_name}`)
        })
      }
    },
  ]
}
```

But my app has about 100k users, so I want to divide sitemap-users.xml into the specified size. (e.g. `sitemap-users-1.xml` `sitemap-users-2.xml`)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c126">#c126</a>)</em></sub></div>

**Comment by atinux** [comment]
I believe the root `sitemap` property can be an async function, so it should fix your issue.

**Comment by NicoPennec** [comment]
@hareku as explain in the [doc "configuration" ](https://sitemap.nuxtjs.org/guide/configuration#function), you can set a function as config.

But it seems you want set a "sitemap index" in your initial request, so check this [doc "sitemap index"](https://sitemap.nuxtjs.org/usage/sitemap-index#setup-a-sitemap-index)

**Comment by hareku** [comment]
Thank you. I can use Promise at `sitemap` property.
