### ISSUE TITLE
sitemap.xml not accessible

### ISSUE THREAD

**Issue by alfaben12** [nuxt-community/sitemap-module#180]
@nuxtjs/sitemap just work for spa mode only? 
I'am trying for ssr mode sitemap.xml not accessible, just showing 404 page

**Comment by NicoPennec** [comment]
As explained in the 1st page of the [sitemap-module documentation](https://sitemap.nuxtjs.org/):
> Works with all modes (SSR, SPA, generate)

If you have an issue, please create a more precise issue with all the details to reproduce : extract of source code, version of nuxt & sitemap module, your nuxt configuration, your context, etc.
