### ISSUE TITLE
generate sitemap automatically without build again for dynamic routes.

### ISSUE THREAD

**Issue by farshidrezaei** [nuxt-community/sitemap-module#186]
generate sitemap automatically without build again for dynamic routes.

i returned a promise that in that, i get dynamic routes by axios.  but if i change any route in backend, sitemap not update until i rebuild nuxt app.

how i can generate sitemap on runtime?

**Comment by tol64** [comment]
Try this one: https://github.com/nuxt-community/sitemap-module/issues/79#issuecomment-788044947

But there is also the problem of dynamic formation of the **sitemapindex** file. I described it in more detail at the link above.

**Comment by NicoPennec** [comment]
@farshidrezaei By default the [`cacheTime` option](https://sitemap.nuxtjs.org/usage/sitemap-options#cachetime-optional---number) is define at 15min. Try to reduce this value as per your convenience.

Eg. set the minimal value of `1 ms` as below:

```js
sitemap: {
  cacheTime: 1,
  // example of dummy dynamic route to check the freshness
  routes: () => {
    return [
      { url: new Date().toISOString() }
    ]
  }
}
```
