### ISSUE TITLE
Can not set priority

### ISSUE THREAD

**Issue by DanSnow** [nuxt-community/sitemap-module#187]
### Reproduction link

[N/A](N/A)

### Steps to reproduce

I want to set the priority like [this](https://sitemap.nuxtjs.org/usage/sitemap#setup-a-sitemap) with `generate.routes`

### What is expected ?

The output sitemap.xml will have `priority` field

### What is actually happening?

Could not find the `priority` field.

### Additional comments?

I believe it's because [here](https://github.com/nuxt-community/sitemap-module/blob/dev/lib/cache.js#L88) omits all the properties except the url. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c134">#c134</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
You can set the `priority` directly in the `generate.routes` config as follows and it works fine with the sitemap module:

```js
  generate: {
    routes: [{ url: 'test', priority: 1 }],
  },
```

In addition, you can set a default priority in the sitemap config as below:
```js
  sitemap: {
    defaults: {
    priority: 1,
  },
```
(see [docs about `defaults` option](https://sitemap.nuxtjs.org/usage/sitemap-options#defaults-optional---object))
