### ISSUE TITLE
Generates file in static during generation

### ISSUE THREAD

**Issue by bayssmekanique** [nuxt-community/sitemap-module#2]
The `sitemap.xml` file is added to the `/static` directory even when being used with the generate function.  It is still being created in the `/dist` directory as well, but it breaks the purely functional nature of the generate function by modifying a file that is in a version controlled directory.

Is there opposition to having it be placed directly into the `/dist` directory?

**Comment by pi0** [comment]
Hi @bayssmekanique. While i totally agree with problem you have mentioned, this is sometimes the only thing we can do for special files like `sitemap.xml` or `sw.js` which should be served from the root `/`. (The files in the `/dist` are prefixed with `_nuxt`). So the simple workaround is adding `static/sitemap.xml` to `.gitignore` file. If you have any better option.

**Comment by bayssmekanique** [comment]
Yes, I understand what you are saying, and I've already added the file to the `.gitignore`.  I was more curious if there was a reason it was placed there beyond simply to facilitate the build steps.

Perhaps a note should be placed in the readme to advise that this is an effect and recommend adding the path to user's `.gitignore` file?

**Comment by pi0** [comment]
> If there was a reason it was placed there beyond simply to facilitate the build steps

Because nuxt currently has not any facilitate for modules providing **static** assets :))

> Perhaps a note should be placed in the readme to advise that this is an effect and recommend adding the path to user's .gitignore file?

Yeah. Is a good idea

**Comment by TrurlMcByte** [comment]
Need just to replace hardcoded ```'static'``` with ```this.options.dir.static``` in code
