### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by yangchendoit** [nuxt-community/sitemap-module#20]
![image](https://user-images.githubusercontent.com/27750211/37819815-c15ee686-2eb9-11e8-9016-ac811baf4645.png)
![image](https://user-images.githubusercontent.com/27750211/37819848-de4a8502-2eb9-11e8-93b8-bd8ec4c2f6a6.png)

when i go back to 0.0.3, the problem fixed. 

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/sitemap-module/issues/c17">#c17</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
sorry it's a regression from v0.0.4 😕 

you can force the previous version while waiting for a fix: `npm install @nuxtjs/sitemap@0.0.3 --save`

**Comment by NicoPennec** [comment]
fixed in v0.0.5
