### ISSUE TITLE
Feature request: HTML version

### ISSUE THREAD

**Issue by Triloworld** [nuxt-community/sitemap-module#206]
XML format is nice,
Maybe HTML will be added as well for humans?
I mean: Using built in page but can be override - module will work like error page.
Injecting data and giving option to style.

By default maybe use ```<details>``` to create proper dom tree.

**Comment by NicoPennec** [comment]
Hi @Triloworld,

An XML sitemap file is generated for crawlers (google bot, bing bot, ...), not for human.

But you can use an [XSL file to customise the XML rendering as an HTML page](https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor/Generating_HTML) and use the [`xslUrl ` sitemap option](https://sitemap.nuxtjs.org/usage/sitemap-options#xslurl-optional---string) to apply it on your sitemap.

**Comment by Triloworld** [comment]
So how to generate it after module generate sitemap? There isn't any hook to provide proper handling with provide generated xml and directory to manipulate data and generate any additional output (this will close any releated issues in that field).
If there is URL and public Hook then I can listen and respond to it with XSL file in same directory with my own module. That's correct?
