### ISSUE TITLE
No XML sitemap generated

### ISSUE THREAD

**Issue by ManasMadrecha** [nuxt-community/sitemap-module#209]
### Version

[^2.4.0](https://github.com/sitemap-module/releases/tag/^2.4.0)

### Reproduction link

[https://github.com/jainism-portal/jainaagam/blob/6f3d7c3befb11b6ef4d394a74a96cefe7fd80ea9/nuxt.config.js#L144](https://github.com/jainism-portal/jainaagam/blob/6f3d7c3befb11b6ef4d394a74a96cefe7fd80ea9/nuxt.config.js#L144)

### Steps to reproduce

1. install nuxt sitemap and nuxt content modules
2. Use the code given on https://content.nuxtjs.org/integrations/#nuxtjssitemap website.
3. Check the reproduction link.

### What is expected ?

To see at least some XML related tags.

### What is actually happening?

The current sitemap being generated is showing just a huge ugly list of URLs without any tags or spacing.

![Screenshot 2021-06-12 060542 Jain Aagam sitemap issue.png](https://cmty.s3.eu-west-1.amazonaws.com/101696111/3a01af00-cb16-11eb-9771-27c3227ceb3d.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c144">#c144</a>)</em></sub></div>

**Comment by ManasMadrecha** [comment]
Found this:

https://stackoverflow.com/questions/61969900/nuxt-sitemap-not-working-properly-when-used-with-nuxt-i18n

It says it's only the browser issue, because in viewsource, you can see the tags and all properly. 😊✅

**Comment by NicoPennec** [comment]
@ManasMadrecha yes, it's a browser rendering issue. That my answer on Stackoverflow 😉
