### ISSUE TITLE
Failed on open /sitemap.xml in production server (404 page)

### ISSUE THREAD

**Issue by helderferrari2** [nuxt-community/sitemap-module#210]
When I try to access /sitemap.xml in my localhost it works well.
However, in my production server, I get a 404 not found page.

**Settings**
`Ubuntu server, Apache2, Nuxt.js (mode: universal), Pm2`

**The server folder contains these files:**
```
/var/www/html/app
    .env 
    .nuxt 
    package.json 
    nuxt.config.js
```

**Apache2 Virtual Host**
```
<VirtualHost *:80>
    ServerName www.site.com
    #ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html/app

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    # has Nuxt runs on port 3000
    ProxyPass / http://localhost:3000
    ProxyPassReverse / http://localhost:3000
</VirtualHost>
```

**pm2 is serving my app with this command:**
`pm2 start app`

**nuxt.config.js**
```
modules: ['@nuxtjs/sitemap'],

  // Sitemap: https://www.npmjs.com/package/@nuxtjs/sitemap
  sitemap: {
    path: '/sitemap.xml',
    hostname: process.env.APP_URL,
    gzip: true,
    exclude: [
      '/login'
      '/profile',
    ],
    routes: async () => {
      const { data } = await axios.get(`${process.env.API_URL}/fetchAllCities`)
      return data.map(item => `products/${item.slug}`)
    }
  }
```

I read about it and I tried to find any solution but without success.
https://github.com/nuxt-community/sitemap-module/issues/163

Does anyone have any idea?

**Comment by MathanKA** [comment]
I am also facing the same issue now. Can anyone please suggest a solution?

**Comment by ChristianGerdes** [comment]
Anything?

**Comment by helderferrari2** [comment]
Yes, guys, I finally solved it.
So basically, there was a .httacess in my root directory redirecting some requests to an error page.

Please check this post:
https://medium.com/@helderferrari2/how-i-deployed-my-nuxt-universal-application-on-a-vps-80c0227dd2a8
