### ISSUE TITLE
cmty.app is down, cannot create new issue

### ISSUE THREAD

**Issue by olets** [nuxt-community/sitemap-module#213]
The issue template says:

> IMPORTANT: Please use the following link to create a new issue:
>
> https://cmty.app/nuxt/issues/new?repo=sitemap-module
>
> If your issue was not created using the app above, it will be closed immediately.

That website has been down for over half a day

![screenshot of error message](https://user-images.githubusercontent.com/3282350/126664067-3bfcdd31-af13-4a87-9952-d4e96daaf2f8.png)

> You've requested a page on a website (cmty.app) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (cmty.app).

**Comment by atinux** [comment]
Sorry about this, I removed the ISSUE_TEMPLATE, should be good now to create issues from GitHub :grinning:
