### ISSUE TITLE
Support server request.headers context

### ISSUE THREAD

**Issue by workingxx92** [nuxt-community/sitemap-module#216]
Hello, 
I need access req.headers.host before call.

const axios = require('axios')

{
  sitemap: {
    routes: async () => {
       **access req.headers.host  at here**
      const { data } = await axios.get('https://jsonplaceholder.typicode.com/users')
      return data.map((user) => `/users/${user.username}`)
    }
  }
}
Thank

**Comment by workingxx92** [comment]
@danielroe .
Can you help me?
Thank

**Comment by NicoPennec** [comment]
@workingxx92 it's not possible, according the current cache system of the module.

**Comment by NicoPennec** [comment]
duplicate with #111
