### ISSUE TITLE
Cannot read property 'filter' of null

### ISSUE THREAD

**Issue by peterkimzz** [nuxt-community/sitemap-module#220]
Hi.
Here is my sitemap async routes function. (in nuxt ssr mode)

Everything is fine when I run my app in dev mode.
But error is occurred in prod mode.

```js
{
  sitemap: {
    hostname: "https://www.domain.com",
    exclude: ["/error", "/sign-up", "/profile", "/settings"],
    routes: async () => {
      try {
        const url =
          process.env.NODE_ENV === "production"
            ? "https://api.domain.com"
            : "http://localhost:3000";

        const { data } = await axios({
          method: "GET",
          url: url + `/v1/sitemap`,
        });

        const sitemap = data.data?.sitemap || [];

        return sitemap;
      } catch (err) {
        return [];
      }
    },
  },
}
```

ERROR  Cannot read property 'filter' of null
at node_modules/@nuxtjs/sitemap/lib/routes.js:14:21
at Array.forEach (<anonymous>)
at excludeRoutes (node_modules/@nuxtjs/sitemap/lib/routes.js:11:12)
at Object.cache.staticRoutes (node_modules/@nuxtjs/sitemap/lib/middleware.js:52:30)
at AsyncCache.load [as _load] (node_modules/@nuxtjs/sitemap/lib/cache.js:19:68)
at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by NicoPennec** [comment]
Hi @peterkimzz,

First, can you try to add a "console.log(sitemap)" to double check the `sitemap` variable is not empty on your prod env ?

Then can you give us more details about your deployment process (cloud provider, commands run, etc.)  to try to reproduce your issue ?

**Comment by peterkimzz** [comment]
Hi @NicoPennec,

The fetched data set is normal array type. 
(e.g. ['/a', '/b', '/c', ...])

Actually my nuxt app is deployed on Vercel Serverless functions.
But There was no issue when I deployed the app on AWS EC2.

Vercel serverless is my suspicious point. 
Because every other modules are working fine just except for sitemap module.

**Comment by NicoPennec** [comment]
Ok it's a Vercel configuration issue so.
The sitemap module documentation will add more details coming soon.
For now, see the right configuration here: https://github.com/nuxt-community/sitemap-module/issues/106#issuecomment-603533758

**Comment by peterkimzz** [comment]
OMG.. you are my savior!!

It works. Thank you so much, @NicoPennec .
