### ISSUE TITLE
Does it support nuxtjs3?

### ISSUE THREAD

**Issue by todaynogada** [nuxt-community/sitemap-module#246]
Does it support nuxtjs3? nuxtjs guide command to If you follow the guide then npm run build and npm run start will not create sitemap.xml.

**Comment by kstraszewski** [comment]
I've also waiting for this update 🙏🏻

**Comment by thinkmoon** [comment]
I've also waiting for this update 🙏🏻

**Comment by severinkilchhofer** [comment]
I've also waiting for this update 🙏🏻

**Comment by gatheluck** [comment]
I've also waiting for this update 🙏🏻

**Comment by thoth3x** [comment]
I've also waiting for this update 🙏🏻

**Comment by d3xter-dev** [comment]
https://github.com/nuxt-community/sitemap-module/issues/248#issuecomment-1129125835

**Comment by codeflorist** [comment]
one might check out https://github.com/benoitdemaegdt/nuxt3-sitemap for a sitemap-solution for nuxt3.

**Comment by d3xter-dev** [comment]
We finally finished a first version for Nuxt 3, feel free to check it out. :tada: 

`yarn add @funken-studio/sitemap-nuxt-3 `

https://github.com/funken-studio/sitemap-module-nuxt-3/tree/experimental
https://www.npmjs.com/package/@funken-studio/sitemap-nuxt-3

**Comment by provokcx** [comment]
> We finally finished a first version for Nuxt 3, feel free to check it out. 🎉
> 
> `yarn add @funken-studio/sitemap-nuxt-3 `
> 
> https://github.com/funken-studio/sitemap-module-nuxt-3/tree/experimental https://www.npmjs.com/package/@funken-studio/sitemap-nuxt-3

@pi0 Will these updates be added to this repository?

**Comment by pascalwengerter** [comment]
Wanted to voice my interest in this issue as well, migrating my employers website to Nuxt3 in the upcoming weeks

**Comment by nicolas-bastien** [comment]
Hi @pi0, as Nuxt3 is stable now do you have planned to migrate this modules ?

Thanks a lot for your highlights
Nicolas

**Comment by algora-pbc** [comment]
💎 **$500** bounty created by @drewbaker
👉 To claim this bounty, [submit your pull request on Algora](https://console.algora.io/bounties/cliqbusbe0012mo0fw2oeci40)
📝 Before proceeding, please make sure you can [**receive payouts**](https://docs.algora.io/bounties/payments#country-support) in your country
💵 Payment arrives in your account 2-5 days after the bounty is rewarded
💯 You keep 100% of the bounty award
🙏 Thank you for contributing to nuxt-community/sitemap-module!

**Comment by codeflorist** [comment]
Check out https://github.com/harlan-zw/nuxt-simple-sitemap.
Harlan is a core member of Nuxt btw.

**Comment by harlan-zw** [comment]
Thanks @codeflorist 

We've discussed as a team that [nuxt-simple-sitemap](https://github.com/harlan-zw/nuxt-simple-sitemap) will likely become the recommendation for Nuxt 3.

Expect an update soon.

Would be great to chat with you about your future involvement in maintaining this module. Please get in touch if you see this :)

**Comment by harlan-zw** [comment]
As the author of this module didn't get back to me, I've marked this as Nuxt 2 and have added [Nuxt Simple Sitemap](https://github.com/harlan-zw/nuxt-simple-sitemap) as the alternative.

I've opened a new [issue](https://github.com/nuxt-community/sitemap-module/issues/292) to track and redirect users.

**Comment by NicoPennec** [comment]
Thanks @harlan-zw  (you have tag the wrong Nicolas previously)

**Comment by harlan-zw** [comment]
> Thanks @harlan-zw (you have tag the wrong Nicolas previously)

Oops, sorry!
