### ISSUE TITLE
Generate dynamic sitemap with axios-module ($axios)

### ISSUE THREAD

**Issue by wolle404** [nuxt-community/sitemap-module#25]
Hey there,

is there a way that I can use the nuxt axios client here instead of the normal axios client?

https://github.com/nuxt-community/axios-module

**Comment by luminous8** [comment]
@wolle404 I'm looking to do this also, did you find a way?

**Comment by msonowal** [comment]
This is definitely required as the proxy config and other authorization things can be shared

did you guys find any 
@chriswdmr @luminous8

**Comment by NicoPennec** [comment]
Sorry but it's currently not possible to use module instances in `nuxt.config.js`.

See this related comment: https://github.com/nuxt-community/axios-module/issues/242#issuecomment-544923463
