### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by ghost** [nuxt-community/sitemap-module#256]
Hello

I'm trying to setup my sitemap. I'm using dynamic routes :

``
  sitemap: {
    lastmod: new Date(),
    routes: async () => {
      const { data } = await axios({ url: 'http://localhost:8080/ei/liste', method: 'GET' })
      return data.map(e => `/user/${e.name}`)
    }
  }
``

But when my sitemap.xml is building, I got this error:

connect ECONNREFUSED 127.0.0.1:8080

Why? This url is public
Thanks

**Comment by NicoPennec** [comment]
Issue on your network access, not related to the module
