### ISSUE TITLE
URLs are missing trailing-slash at the end

### ISSUE THREAD

**Issue by ma-vo** [nuxt-community/sitemap-module#268]
Your auto-generated sitemap creates URLs which lead to sites of the status 301 (permanently redirected). This lead to confused or even broken crawlers. Most of the crawlers are expacting a status of 200 (ok).

This URL is generated by your module:
https://DOMAIN.com/subpage 
This URL would be correct
https://DOMAIN.com/subpage/

The ending trailing-slash is mandatory.

**Comment by NicoPennec** [comment]
Nuxt 2.x generate each route without trailing-slash by default. the root cause is not about the sitemap module.

But the module have a `trailingslash` option to handle that (and read details about 301 in the docs):
https://sitemap.nuxtjs.org/usage/sitemap-options#trailingslash-optional---boolean

**Comment by ma-vo** [comment]
Great! Missed that option. Thanks @NicoPennec
