### ISSUE TITLE
Dynamically generated routes are not excluded

### ISSUE THREAD

**Issue by madiyetov** [nuxt-community/sitemap-module#288]
## Description

If we pass `exclude` property with glob pattern for dynamically generated routes, it's not applied:
```javascript
export default {
   sitemap: {
      exclude: ['**/dynamic-route']
   }
}
``` 

In [this line](https://github.com/nuxt-community/sitemap-module/blob/dev/lib/cache.js#L19), the pattern from `exclude` is applied inside `staticRoutes` to static routes, but routes coming from `promisifyRoute(options.routes)` are not filtered.

nuxt@2.17.0

**Comment by NicoPennec** [comment]
Hi @madiyetov,

As explained in the documentation of [`exclude` property](https://sitemap.nuxtjs.org/usage/sitemap-options#exclude-optional---string-array), it's only to exclude routes from `staticRoutes`, before caching data (see [here](https://github.com/nuxt-community/sitemap-module/blob/dev/lib/generator.js#L50))

if you need to exclude some dynamics routes, you have to customize your [`routes` function](https://sitemap.nuxtjs.org/usage/sitemap-options/#routes-optional---array--function) or use the [`filter` function](https://sitemap.nuxtjs.org/usage/sitemap-options/#filter-optional---function).
