### ISSUE TITLE
What about alternate language pages?

### ISSUE THREAD

**Issue by OlegLevitskiy** [nuxt-community/sitemap-module#29]
How to add a multi-language to the sitemap configuration?
```
 links: [
  { lang: 'en', url: 'http://test.com/page-1/', },
  { lang: 'ja', url: 'http://test.com/page-1/ja/', }
 ]
```

**Comment by abrantes01** [comment]
Hey @OlegLevitskiy , 

Did you find a way to a multi-language to the sitemap configuration ? 

How could we integrate this plugin with the nuxtI18n one to automatically generate the sitemap with alternates pages generated by nuxtI18n ?

**Comment by thariddler** [comment]
Looking for the same solution. What to do?

**Comment by NicoPennec** [comment]
@OlegLevitskiy you can use the `links` attribute.

see https://github.com/nuxt-community/sitemap-module/issues/39#issuecomment-464328102
