### ISSUE TITLE
help: sitemap-lastmod feature is forced to transfer iso type

### ISSUE THREAD

**Issue by FairyFanFan** [nuxt-community/sitemap-module#297]
nuxt2
nuxtjs sitemap v2.4.0
how can i set lastmod as '2024-01-01' rather than iso type

**Comment by NicoPennec** [comment]
See my answser here: https://github.com/nuxt-community/sitemap-module/issues/219#issuecomment-2255327884

**Comment by FairyFanFan** [comment]
> See my answser here: [#219 (comment)](https://github.com/nuxt-community/sitemap-module/issues/219#issuecomment-2255327884)

sorry but  it doesn't work  
source code in v2.4.0 are "normaliseDate(e.lastmod)", normalise function force date string transfer to iso type
