### ISSUE TITLE
image, video ... url in sitemap

### ISSUE THREAD

**Issue by miladmeidanshahi** [nuxt-community/sitemap-module#3]
Hi @pi0,

how to send image and video url in this function ?
```
const axios = require('axios')

module.exports = {
  sitemap: {
    routes () {
      return axios.get('https://jsonplaceholder.typicode.com/users')
      .then(res => res.data.map(user =>  '/users/' + user.username))
    }
  }
}
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/sitemap-module/issues/c3">#c3</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
your route should respect the following format:

```
      {
        url: '/page/videos',
        video: [
          { thumbnail_loc: 'http://test.com/tmbn1.jpg', title: 'A video title', description: 'This is a video' },
          { thumbnail_loc: 'http://test.com/tmbn2.jpg', title: 'Another video title', description: 'This is another video' },
        ]
      }
```

More details on the `sitemap` lib : https://github.com/ekalinin/sitemap.js#example-of-videos

**Comment by miladmeidanshahi** [comment]
many thanks @NicoPennec but can you show me how can i use this data in this function ?

```
const axios = require('axios')

module.exports = {
  sitemap: {
    routes () {
      return axios.get('https://jsonplaceholder.typicode.com/users')
      .then(res => res.data.map(user =>  '/users/' + user.username))
    }
  }
}
```

**Comment by thinguyennam4059605** [comment]
same issues. How to seo image dynamic?

**Comment by mdespeuilles** [comment]
Same issue for me :-)
If anybody have an idea

**Comment by NicoPennec** [comment]
@miladmeidanshahi @thinguyennam4059605 @mdespeuilles 

Here an example to return dynamic images:

```js
  sitemap: {
    hostname: 'https://example.com/',
    routes: async () => {
      // fetch user data
      const { data } = await axios.get('https://jsonplaceholder.typicode.com/users')

      return Promise.all(
        data.map(async (user) => {
          // fetch user image
          const { data } = await axios.get(`https://jsonplaceholder.typicode.com/photos/${user.id}`)

          // return url + array of image
          return {
            url: '/users/' + user.username,
            img: [
              {
                url: data.url,
                title: data.title,
              },
            ],
          }
        })
      )
    },
  },
```

and the result:

```xml
<url>
  <loc>https://example.com/users/Bret</loc>
  <image:image>
    <image:loc>https://via.placeholder.com/600/92c952</image:loc>
    <image:title>
      <![CDATA[ accusamus beatae ad facilis cum similique qui sunt ]]>
     </image:title>
  </image:image>
</url>
<url>
  ...
</url>
```

**Comment by BerciTheBeast** [comment]
Is there a way to make it gather the images from the static pages as well or define the images on the static pages themselves?

**Comment by vanhoinguyen1998** [comment]
> @miladmeidanshahi @thinguyennam4059605 @mdespeuilles
> 
> Here an example to return dynamic images:
> 
> ```js
>   sitemap: {
>     hostname: 'https://example.com/',
>     routes: async () => {
>       // fetch user data
>       const { data } = await axios.get('https://jsonplaceholder.typicode.com/users')
> 
>       return Promise.all(
>         data.map(async (user) => {
>           // fetch user image
>           const { data } = await axios.get(`https://jsonplaceholder.typicode.com/photos/${user.id}`)
> 
>           // return url + array of image
>           return {
>             url: '/users/' + user.username,
>             img: [
>               {
>                 url: data.url,
>                 title: data.title,
>               },
>             ],
>           }
>         })
>       )
>     },
>   },
> ```
> 
> and the result:
> 
> ```
> <url>
>   <loc>https://example.com/users/Bret</loc>
>   <image:image>
>     <image:loc>https://via.placeholder.com/600/92c952</image:loc>
>     <image:title>
>       <![CDATA[ accusamus beatae ad facilis cum similique qui sunt ]]>
>      </image:title>
>   </image:image>
> </url>
> <url>
>   ...
> </url>
> ```

I want to  result <image:title> is String , not XML. Is there any way to do it?

**Comment by hoojinguyen** [comment]
I want to result image:title is String , not XML. Is there any way to do it?

**Comment by NicoPennec** [comment]
@vanhoinguyen1998 the `<![CDATA[ ... ]` notation is applied by the sitemap node lib used under the hood.

But a sitemap is an XML file, a `<image:title>` is an XML element, a `CDATA` is an XML notation.
So it's not a problem, it's a valid sitemap.
