### ISSUE TITLE
How to use this module?

### ISSUE THREAD

**Issue by JanuszOsica** [nuxt-community/sitemap-module#31]
Hi,
I'm install and require this module to nuxt.config.js, but when i use nuxt generete then sitemap is not generated, with and without sitemap config. How to use it?

**Comment by NicoPennec** [comment]
as explained on [README](https://github.com/nuxt-community/sitemap-module) documentation, you have to set `generate: true` in your `nuxt.config.js` file  😉

**Comment by juanvillegas** [comment]
@NicoPennec What if I want it to not run at all during build? Ideally, I'd like to execute it when the first user requests it, and then use the cache version after that. Is that possible?

**Comment by NicoPennec** [comment]
@juanvillegas if your are in SSR mode instead of Generate mode, this is the expected operation. But in Generated mode is technically impossible because the build is executed only once.
