### ISSUE TITLE
Feature request: add last modification date

### ISSUE THREAD

**Issue by derevandal** [nuxt-community/sitemap-module#44]
### What problem does this feature solve?

Adding `<lastmod>2019-01-23</lastmod>` in a `url` tag, search engines will know how this content changed and when it was added and improve the pagerank.

### What does the proposed changes look like?

I suggest to use `fs.stat(path, [callback])` to read `mtime` stat of `.vue`'s file or `.md`'s (I wanna use to a blog system, so, it be helpfull this support) and write in sitemap.xml

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c39">#c39</a>)</em></sub></div>

**Comment by manniL** [comment]
Reading the `mtime` would be perfect for a situation like yours. As soon as you are using an API or similar you can't use that approach though.

Adding `lastmod` already works (see https://blog.lichter.io/sitemap.xml).

I'd leave the implementation up the user.

**Comment by manniL** [comment]
Ah, but there should be a neat way for "static" URLs to provide that. true

**Comment by NicoPennec** [comment]
@derevandal  the `sitemap` npm lib behind the `sitemap-module` offers this feature.

```js
 { url: '/page1', lastmodrealtime: true, lastmodfile: 'page/page1.vue' },
```

see https://github.com/ekalinin/sitemap.js#example-of-pre-generating-sitemap-based-on-existing-static-files

But I never try it, if it meets your needs

**Comment by derevandal** [comment]
@NicoPennec is there a way to make this automatically?
Should I user `filter` option?
Thanks <3

**Comment by NicoPennec** [comment]
@derevandal It depends on your need.

If you targeting only **dynamic** routes, on your sitemap config your can set it directly.

eg.
```js
    routes() {
      const products = ... // fetch your data from anywhere (API, JSON, static file, ...)
      return products.map(product => ({
        url: `/product/${product.slug}`,
        lastmodfile: `data/${product.slug}.md`,
        lastmodrealtime: true
      }))
```

If you have **static** routes to process, the `filter` option is the way to do it. This is a perfect use case for this option, because it will be your own function to readjust your custom routes declarations.

eg.
```js
    filter({ routes }) {
      return routes.map(route => {
        // eg. url = '/product/product-id-1' with the *.md source file = ./data/product-id-1.md
        const slug = route.url.replace('/product/', '')
        route.lastmodfile =  `data/${slug}.md`
        route.lastmodrealtime = true
      });
    }
```
