### ISSUE TITLE
Doesn't create sitemap.xml when running nuxt generate

### ISSUE THREAD

**Issue by adam-lynch** [nuxt-community/sitemap-module#5]
Tell me if I'm missing something here but when I run `nuxt generate`, a `sitemap.xml` file is not created (anywhere). A `dist/_nuxt/sitemap-routes.json` is (and if I run `nuxt` for dev mode, going to `/sitemap.xml` does return work fine) . I've tried using having no `sitemap` property in `nuxt.config.js`, and the example config in the README.
 
sitemap-module: 0.0.3
nuxt: 1.0.0-rc11
OS: Mac

**Comment by NicoPennec** [comment]
Have you put the `generate` option on 'true' in the `nuxt.config.js`?

```json
sitemap: {
  generate: true,
  ...
}
```

**nb:** this option should be set `true` with the generate mode only (else you can remove the line or set `false`).

**Comment by adam-lynch** [comment]
Ha! Of course not, that would be too easy. Thanks 👍

**Comment by liquidvisual** [comment]
I'm running into the same problem. I've set generate to true but no sitemap is appearing. Could I be missing something?

**Comment by NicoPennec** [comment]
@liquidvisual 
can you tell me more about your setup ?
- [ ] node version
- [ ] nuxt version
- [ ] sitemap-module version
- [ ] nuxt mode (ssr, generated, spa, ...)

then, please shared an extract of your `nuxt.config.json` file to check your `sitamap:{ ... }` config.

**Comment by husayt** [comment]
```
  sitemap: {
        path: '/sitemap.xml',
        hostname: 'https://www.alpha.com',
        generate: true, // Enable me when using nuxt generate
        exclude: [],
        routes: []
    },
```

Here is my sample.
