### ISSUE TITLE
HTTPS with req.headers.host icw proxy

### ISSUE THREAD

**Issue by Timkor** [nuxt-community/sitemap-module#56]
### What problem does this feature solve?

I would like to generate `https` links while nuxt runs without ssl. The proxy handles this.

### What does the proposed changes look like?

A new config property which can force the generated links to use https.

https://github.com/nuxt-community/sitemap-module/blob/5d029a29443862bc6f8b5c141b3b01f9312f909c/lib/module.js#L152

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c46">#c46</a>)</em></sub></div>

**Comment by Timkor** [comment]
I solved it by using the `x-forwarded-proto` header in the load balancer.

This is tested by the `is-https` package:
https://www.npmjs.com/package/is-https

Are there plans to keep supporting this in the future?

**Comment by NicoPennec** [comment]
From my point of view, using `x-forwarded-proto` is enough, so it doesn't seem necessary to force https. 

@Timkor why not just set the "hostname" parameter?

```js
sitemap: {
    hostname: 'https://example.com',
    // ...
}
```

**Comment by Timkor** [comment]
@NicoPennec 
Ok, then I will keep it that way.

I have multiple domains connected to my nuxt app. Like:

```
example.com
example.de
example.fr
example.it
example.es
```

**Comment by NicoPennec** [comment]
@Timkor I closed the initial topic. But you have an interesting use case and so I need more details for a future feature 😉 

Do you need multiple sitemaps or always the same sitemap for each domain name (except for a dynamic hostname) ?
