### ISSUE TITLE
The meaning of the exclude parameter is not clear.

### ISSUE THREAD

**Issue by ilyaskorik** [nuxt-community/sitemap-module#65]
Judging by the code, it filters the routes of nuxt, and not the final xml file data. In my case it does not work. Can you fix this and filter the final data?

**Comment by NicoPennec** [comment]
As explain in the README, the `exclude` parameter is only for the static routes generated by Nuxt (see https://nuxtjs.org/guide/routing#basic-routes).
Else you can use the `filter` parameter to filter the any data before the sitemap generation.

Can you be more explicit about your need? (eg. give an example of use case)

**Comment by siolfyr** [comment]
But why, though? He's right, it is unclear. It's going to keep confusing people as long as it's this way. Names should always make sense, and *exclude* implies that you will exclude the routes within... it's not *staticExclude* or something like that.
