### ISSUE TITLE
Support sitemap creation when using generate payload

### ISSUE THREAD

**Issue by Jered** [nuxt-community/sitemap-module#68]
### What problem does this feature solve?

When using generate with dynamic routes you return the routes as an array of string URLs which the sitemap module picks up and creates a correct sitemap.xml. However, if you return the routes object from generate to use the [payload feature](https://nuxtjs.org/api/configuration-generate/#speeding-up-dynamic-route-generation-with-code-payload-code-), the sitemap will fail because it expects a string instead of an object.

### What does the proposed changes look like?

Make it so sitemap can use `generate.routes` when using payloads. Should be updated to also accept routes in the form of:
```
[
  {
    route: 'urlstring', 
    payload: {data object},
    ...
  }
]
```

and extract the route.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c52">#c52</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Hi @Jered 
Thanks for your request 👍 

Can you create and share a simple Nuxt project to reproduce the payload issue, please?
This will help to test a fix.

**Comment by NicoPennec** [comment]
Issue fixed on release **[v1.3.1](https://github.com/nuxt-community/sitemap-module/blob/master/CHANGELOG.md#131-2019-09-17)**

**Comment by Jered** [comment]
Thanks for the fix! Sorry, I have been busy and haven't been able to create a test. I'll test on our project.

**Comment by NicoPennec** [comment]
Thanks. Let me know if you have any bugs.
