### ISSUE TITLE
Filter function should receive the full route object (instead of just the url)

### ISSUE THREAD

**Issue by SnirShechter** [nuxt-community/sitemap-module#69]
### What problem does this feature solve?

The filter function receives an array of routes containing URLs and sitemap options. This means that the only way to filter the route is by final URL:

#### filter function - received route object
```javascript
{
      url:'/about-us',
      // ...sitemapOptions
}
```

The specific need rises when we are using nuxt-i18n:
#### localed route
```javascript
routeName: 'about'
urls:{
      en: '/about-us', 
      fr: '/a-propos',
      es: '/sobre' 
}
```

If I wish to exclude these routes, I need to use one of two options:
#### sitemapConfig - exclude 'about'
```javascript
exclude: [
      '/about-us', 
      '/a-propos',
      '/sobre'
]
```
or
#### filter function - exclude 'about'
```javascript
filter(routes){
      const excludedRoutes =  ['/about-us', '/a-propos', '/sobre']
      return routes.filter(route=>!excludedRoutes.includes(route.url))
}
```

### What does the proposed changes look like?

The route object can actually contain more data:
#### filter function - possible route object
```javascript
{
      url:'/about-us',
      name:'about',
      path:'/',
      chunkName:'pages/index',
      component:'C:\dev\sitemap-module\test\fixture\pages\about.vue'
}
```

Using that data, we can easily exclude routes by name.
#### filter function - new form
```javascript
filter(routes){
      const excludedRouteNames =  ['about']
      return routes.filter(route=>!excludedRouteNames .includes(route.name))
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c53">#c53</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
@SnirShechter, @NicoPennec 
In version 2.0.0 the route is coming as an object, I think it can close.

**Comment by ricardogobbosouza** [comment]
@NicoPennec  can closed?

**Comment by NicoPennec** [comment]
@ricardogobbosouza no, it's not that.

**Comment by NicoPennec** [comment]
@SnirShechter I just cherry-picked your commit from your still remained opened PR #70

Thank you for this contribution 🙏
