### ISSUE TITLE
Force https urls

### ISSUE THREAD

**Issue by starikovm** [nuxt-community/sitemap-module#84]
### What problem does this feature solve?

I have a website running on https on heroku, so https request via CNAME goes to herou and website is hosted there.
What am I experiencing now is that `isHTTPS(req)` function on production is returning false for these kind of requests, probably because of current hosting architecture.

I wanted to raise a PR with an option for forced https links in sitemap to avoid such issues and such situations.

### What does the proposed changes look like?

Option in sitemaps module like `forceHTTPS`, which then creates all links with https reagrdless of request type and so on.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c69">#c69</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Your issue seems duplicate from that one: https://github.com/nuxt-community/sitemap-module/issues/56

2 solutions:

* set an `hostname` value in your `nuxt.config.js`
```js
sitemap: {
    hostname: 'https://example.com',
    // ...
}
```

* Try to to enable https with a  `x-forwarded-proto` header
see `is-https` doc https://www.npmjs.com/package/is-https#behaviour

**Comment by starikovm** [comment]
@NicoPennec hostname is not an option, cause I have multi-domain website for different languages.
I ll investigate is-https package, thanks!

**Comment by ricardogobbosouza** [comment]
@NicoPennec can closed?

**Comment by NicoPennec** [comment]
yes, the `x-forwarded-proto` header is the right way if the hostname cannot be setted.
