### ISSUE TITLE
Consider Router Base

### ISSUE THREAD

**Issue by mojtaba06** [nuxt-community/sitemap-module#88]
### What problem does this feature solve?

If defined the router base in nuxt.config.js file, the links in the sitemap file did not consider that.
router: {
        base: '/something/'
}

### What does the proposed changes look like?

When creating the links in the sitemap file, It would be nice that consider the router base to make the real link.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c72">#c72</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Good catch!
It's a very old bug :scream:
Thanks for your report @mojtaba06 :pray: 

I will fix it ASAP.

**Comment by mojtaba06** [comment]
@NicoPennec Your welcome. Thanks for your attention and also for the useful module you wrote.

**Comment by NicoPennec** [comment]
Issue fixed on release **[v2.0.1](https://github.com/nuxt-community/sitemap-module/blob/master/CHANGELOG.md#201-2019-11-12)**

**Comment by mareestephan** [comment]
Is there an option to remove the router: {
base: '/something/'
}

when the sitemap links are generated? 
eg. example.com/something/dynamicRoute/dynamicRoute/ 
it would be great to change /something/ to a string relating to the dynamic route selected.

Example below: Would like to change /juno/ to /ssi/
<img width="344" alt="Screen Shot 2020-10-09 at 15 50 36" src="https://user-images.githubusercontent.com/35425202/95591151-38648680-0a47-11eb-892e-cd60b82f2b8d.png">
<img width="862" alt="Screen Shot 2020-10-09 at 15 49 43" src="https://user-images.githubusercontent.com/35425202/95591160-3ac6e080-0a47-11eb-9386-e857892150bd.png">
<img width="522" alt="Screen Shot 2020-10-09 at 15 49 30" src="https://user-images.githubusercontent.com/35425202/95591168-3c90a400-0a47-11eb-98d8-668ed1f07804.png">
